name: CI

on: [push]

jobs:
    test:
        name: Check
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: Setup PHP with composer v2
          uses: shivammathur/setup-php@v2
          with:
              php-version: '8.2'
              tools: composer
        -
          name: Install dependencies
          run: composer install
        -
          name: Tests without extension
          run: ./phpunit --configuration phpunit.xml.without-extension
        -
          name: Tests with extension
          run: ./phpunit
